apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::288206953113:role/codebuild-brain-tasks-service-role
      username: codebuild
      groups:
        - system:masters
    - rolearn: arn:aws:iam::288206953113:role/service-role/codebuild-brain-tasks-app-build-service-role
      username: codebuild-service
      groups:
        - system:masters

