apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
         - name: brain-tasks-app
           image: 288206953113.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-0a387685215d:latest
           ports:
             - containerPort: 80
